version: '3.8'

services:
    app:
        build:
            context: /home/lanth/Документы/phpmyadmin
            dockerfile: Dockerfile
        container_name: laravel_app_phpmyadmin
        volumes:
            - /home/lanth/Документы/phpmyadmin:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx_server_phpmyadmin
        ports:
            - "8081:80"
        volumes:
            - /home/lanth/Документы/phpmyadmin:/var/www
            - /home/lanth/Документы/phpmyadmin/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - laravel_db_phpmyadmin:db
        ports:
            - "8013:80"
        environment:
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: mysql:8
        container_name: laravel_db_phpmyadmin
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
